### ISSUE TITLE
Decoder API makes no sense for formats like JSON or MessagPack

### ISSUE THREAD

**Issue by jpastuszek** [rust-lang/rustc-serialize#78]
Since JSON and MessagePack both encode type information (array, map, int, float, string, bool and nil) having API that step by step expects some particular type of data is very inflexible and quite useless in real life scenarios.

The power of this two formats compared to formats that needs external schema definition to work is that they offer extended flexibility and backward compatibility by providing type information within the actual data.
This in turn allows one to map JSON or MessagePack messages onto structures even when the fields are in different order, there are extra fields or even use different data types (like int for float) where you can simply handle them by casting or actually expect them and use enums to store them in your structure.

With current API the message is expected to exactly follow you decoding code and any variation like different key order, extra keys or different type will cause error that you cannot act upon even when it should be possible to extract all the information from the message that you may need.
There is no way to branch (match) based on actual message content.

Now while this style of API is correct for Encoder - you want to dictate exactly what data types and in what order you want to encode in it, decoding needs to be way more flexible then it is now taking that you may not control the source of the messages and some variation in formats like JSON or MessagPack is to be expected and it should be possible to handle thous variations even automatically.

**Comment by BurntSushi** [comment]
@jpastuszek I think "useless" is probably too strong of a word. With that said, you have absolutely described a limitation. One way around this is to use a `Json` type explicitly in the parts of the structure that are unknown, decode into that, do your case analysis and decode from the `Json` type into your appropriate type. The problem is that decoding into `Json` isn't possible with the current `Decoder` API (although you can decode *from* a `Json` type). I think @erickt has fixed that limitation in `rustc-serialize`'s expect successor: https://github.com/erickt/rust-serde

**Comment by jpastuszek** [comment]
With this sort of limitation this API style is more in pair with https://crates.io/crates/bincode format rather than JSON. Presenting JSON as main supported (in tree) format for this API without explicitly pointing out this sort of limitations and then asking users to use implementation detail to work around it is perhaps little disappointing IMHO.
Thank you for pointing me to rust-serde, the README file sums this up very well.
